import os
import json
import torch
import typer
import warnings

import numpy as np
import SimpleITK as sitk

from typing import Tuple, List

from src.sire.utils.affine import transform_points
from src.sire.inference.utils.vessel_config import VesselConfig
from src.sire.inference.utils.step_schedulers import ConstantStepScheduler
from src.sire.inference.totalsegmentator_processor import Roi, TotalSegmentatorProcessor
from src.sire.inference.utils.stopping_criterions import RoiStoppingCriterion, VesselDiameterStoppingCriterion, NotAVesselStoppingCriterion
from src.sire.inference.utils.correction_methods import ParallelTransportFrame

app = typer.Typer()

def world2voxel(seed, ct):
    origin = np.array(ct.GetOrigin())
    spacing = np.array(ct.GetSpacing())
    direction = np.array(ct.GetDirection()).reshape(3,3)

    seed_voxel = np.linalg.inv(direction) @ (seed - origin).T
    seed_voxel = (seed_voxel.T / spacing)
    seed_voxel = np.round(seed_voxel).astype(int)

    return seed_voxel

def voxel2world(seed_voxel, ct):
    origin = np.array(ct.GetOrigin())
    spacing = np.array(ct.GetSpacing())
    direction = np.array(ct.GetDirection()).reshape(3, 3)

    seed_voxel = np.array(seed_voxel, dtype=float)
    seed_world = direction @ (seed_voxel * spacing) + origin

    return seed_world

def save_roi_file(reference_image : str, mask,
                  output_dir : str, 
                  roi : list,
                  name : str = "roi.nii.gz"):
    
    '''Saves the created ROI, if the seeds are provided as a list, 
    '''
    
    roi_array = Roi.intersection(mask, roi_list = roi)
    roi_array = roi_array.astype(np.uint8)
    
    roi_img = sitk.GetImageFromArray(roi_array)
    roi_img.CopyInformation(reference_image)
    os.makedirs(os.path.join(output_dir, "roi"), exist_ok=True)

    sitk.WriteImage(
        roi_img,
        os.path.join(output_dir, "roi", name)
    )

def load_centerpoints(PATH : str):
     
    data = [] 

    with open(PATH, "r") as f: 
        for linea in f: 
            centerpoints = list(map(int, linea.strip().split(","))) 
            data.append(centerpoints)

    return data

def define_roi_CC(mask : np.array,
                  **kwargs) -> Roi:

    '''
    Definition of the ROI for the common carotid, ideally it covers from the brachiocephalic trunk 
    to below C3, this should be just after the bifurcation.
    
    :param mask: Mask generated by TotalSegmentator.
    :type mask: np.array

    :return: Description
    :rtype: Roi
    '''

    use_skull = kwargs.get("use_skull", True)
    use_vertebrae = kwargs.get("use_vertebrae", True)

    roi = []

    labels = {"TRACHEA" : 16, 
              "C1" : 50,
              "C2" : 49,
              "C3" : 48,
              "C1_T2" : [50, 49, 48, 47, 46, 45, 44, 43, 42],
              "T1" : 43,
              "T2" : 42,
              "SKULL" : 91}
    
    if np.any(mask == labels["C1"]): # Just above max point of c1
        roi.append(Roi([labels["C1"]], "below", "max", dilate = 5))

    elif np.any(mask == labels["C2"]): 
        roi.append(Roi([labels["C2"]], "below", "max", dilate = 5))

    if np.any(mask == labels["SKULL"]):

            roi.append(Roi([labels["SKULL"]], "right", "max")) # Cropping to the sides.
            roi.append(Roi([labels["SKULL"]], "left", "min"))
            roi.append(Roi([labels["SKULL"]], "back", "max"))
            roi.append(Roi([labels["SKULL"]], "front", "min"))
            roi.append(Roi([labels["SKULL"]], "below", "max"))

    if not use_skull: # Keeping outside the ROI 
        roi.append(Roi([labels["SKULL"]], "outside")) # Sometimes sticks to the mandible.
            
    vertebrae_found = [np.any(mask == l) for l in labels["C1_T2"]] # We check the mask.
    roi_vertebrae = [l for v, l in zip(vertebrae_found, labels["C1_T2"]) if v] # We only keep the found ones.

    if not use_vertebrae: # Keeping the spinal column outside the ROI.
        roi.append(Roi(roi_vertebrae, "outside"))

    if np.any(mask == labels["T2"]):
        roi.append(Roi([labels["T2"]],
                       "above", "min"))
        
    else:
        for v, l in zip(vertebrae_found[::-1], labels["C1_T2"][::-1]):
            if v: 
                roi.append(Roi([l],
                           "above", "min"))    
            break
    return roi

def get_anatomical_indices(mask : np.array,
                           labels : List[int],
                           ct : sitk.Image) -> dict:
    
    indices = {}
    for label in labels: # Iteration around the provided TotalSegmentator labels.
        if np.any(mask == label):
            
            found_label = np.array(mask == label)
            indx = np.argwhere(found_label)

            idx_min = indx[np.argmin(indx[:,0])]
            idx_max = indx[np.argmax(indx[:,0])]

            indices[label] = {'max_xyz': voxel2world([int(idx_max[2]), int(idx_max[1]), int(idx_max[0])], ct),
                              'min_xyz': voxel2world([int(idx_min[2]), int(idx_min[1]), int(idx_min[0])], ct)}
    return indices

def get_stopping_criterions(params, use_circularity: bool):
    criterions = [
        RoiStoppingCriterion(params["roi"]),
        VesselDiameterStoppingCriterion(
            max_diameter=params["diameter"]["max"],
            min_diameter=params["diameter"]["min"]
        ),
    ]

    if use_circularity:
        criterions.append(
            NotAVesselStoppingCriterion(
                min_circularity=params["circularity"]["min"]
            )
        )

    return criterions

class UMCTotalSegmentatorProcessor(TotalSegmentatorProcessor):
    def __call__(self,
                 image_path : str,
                 output_dir : str,
                 seed_path : str = None,
                 save_roi : bool = False,
                 ts_preprocessing : bool = False,
                 device : str = "cpu"):
         
        # Read, and save the image first.
        # Maybe we can check if this folder exists, that means is the second iteration.

        os.makedirs(os.path.join(output_dir, "reorientedData"), exist_ok=True)
        PATH_saved = os.path.join(output_dir, 
                                  "reorientedData",
                                  "raw_lps_oriented.nii.gz")

        itk_image = sitk.ReadImage(image_path)
        itk_image = sitk.DICOMOrient(itk_image, "LPS") # Re-orient to LPS.

        sitk.WriteImage(itk_image, PATH_saved)

        # Indicates that TotalSegmentator 2.13.0 was used to generate other masks.
        if ts_preprocessing:
            print("\nIn UMC Segmentator")

        mask, affine = self.run(PATH_saved, # This is the path of the image re-oriented.
                                output_dir,
                                device)
        
        roi = define_roi_CC(mask) # Create the ROI.
        if save_roi:
            save_roi_file(itk_image, 
                          mask,
                          output_dir,
                          roi)

        segments = {}

        # try:
        #     if np.any(mask == 57): # We have a mask.
        #         segments["common_carotid_artery_right"] = {"diameter" : {"min": None, "max": 70},
        #                                                    "circularity" : {"min": 0.4},
        #                                                    "roi" : Roi.intersection(mask, roi_list = roi),
        #                                                    "step" : 0.25}             
        #         segments["common_carotid_artery_right"]["seed"] = self._get_seed(mask, 
        #                                                                          affine, 
        #                                                                          segments["common_carotid_artery_right"]["roi"],
        #                                                                          57, p = 0.1)
        # except:
        #     warnings.warn("No seed for the right carotid was found by TotalSegmentator, please provide it manually")

        try:
            if np.any(mask == 58): # We have a mask.
                segments["common_carotid_artery_left"] = {"diameter" : {"min": None, "max": 70},
                                                        "circularity" : {"min": 0.4},
                                                        "roi" : Roi.intersection(mask, roi_list = roi),
                                                        "step" : 0.25}
                segments["common_carotid_artery_left"]["seed"] = self._get_seed(mask, 
                                                                                affine, 
                                                                                segments["common_carotid_artery_left"]["roi"],
                                                                                58, p = 0.25)
        except:
            warnings.warn("No seed for the left carotid was found by TotalSegmentator, please provide it manually.")
            
        if not segments: # We return an empty array since there are not segments to check.
            warnings.warn("Total Segmentator wasn't able to generate proper seedpoints, please provide a seed file.")
            return []
        
        return [
            VesselConfig(
                name = name,
                seed_point = params["seed"],
                segment_every_n_steps = 5,
                step_scheduler = ConstantStepScheduler(params["step"]),
                stopping_criterions = [
                    RoiStoppingCriterion(params["roi"]),
                    VesselDiameterStoppingCriterion(
                        max_diameter = params["diameter"]["max"], min_diameter = params["diameter"]["min"]
                    ),
                    NotAVesselStoppingCriterion(min_circularity = params["circularity"]["min"])
                ],
                centerline_resampling = -1,
                vessel_correction = False
            )
            for name, params in segments.items()], 
    
class UMCTotalSegmentatorProcessorComplete(TotalSegmentatorProcessor):
     
    def __call__(self,
                 image_path : str,
                 output_dir : str,
                 left_seeds : dict = None,
                 right_seeds : dict = None,
                 save_roi : bool = False,
                 device : str = "cuda",
                 **kwargs):
        
        # Getting options of the generation of the ROI.
        normal_ts = kwargs.get("normal_mode_ts", False)
        use_circularity = kwargs.get("circularity_sc", True)

        options = {"use_skull" : kwargs.get("use_skull", True),
                   "use_vertebrae" : kwargs.get("use_vertebrae", True)}
        
        # If normal is enabled, the mask look a little bit better.
        if not normal_ts:
            mask_name = "mask.nii.gz"
        else:
            print("Normal mode is enabled for Total Segmentator, this might take a little bit longer.")
            mask_name = "mask_normal.nii.gz"
        
        mask, _ = self.run(image_path, 
                           output_dir,
                           device = "gpu" if device == "cuda" else "cpu",
                           fast = normal_ts,
                           mask_name = mask_name)

        itk_image = sitk.ReadImage(image_path)
        
        roi = define_roi_CC(mask,
                            **options) # Create the ROI

        if save_roi:
            roi_array = Roi.intersection(mask, roi_list = roi).astype(int)
            roi_array = sitk.GetImageFromArray(roi_array)
            roi_array.CopyInformation(itk_image)
            sitk.WriteImage(roi_array, os.path.join(output_dir, "totalsegmentator", "roi.nii.gz"))

        indices = get_anatomical_indices(mask, 
                                         [50, 49, 48, 47, 46, 45], itk_image)

        # Creating the VesselConfig for the for segments. This can be manual if the seeds were provided.
        segments, step = {}, 0.1 # Now we have four segments.
        
        # For the right side, external and internal VesselConfig
        segments["external_carotid_artery_right"] = {"diameter" : {"min": None, "max": 30},
                                                     "circularity" : {"min": 0.4},
                                                     "roi" : Roi.intersection(mask, roi_list = roi),
                                                     "step" : step} 

        segments["internal_carotid_artery_right"] = {"diameter" : {"min": None, "max": 40},
                                                     "circularity" : {"min": 0.4},
                                                     "roi" : Roi.intersection(mask, roi_list = roi),
                                                     "step" : step}  

        # # For the left side, external and internal VesselConfig
        segments["external_carotid_artery_left"] = {"diameter" : {"min": None, "max": 30},
                                                    "circularity" : {"min": 0.4},
                                                    "roi" : Roi.intersection(mask, roi_list = roi),
                                                    "step" : step}

        segments["internal_carotid_artery_left"] = {"diameter" : {"min": None, "max": 30},
                                                    "circularity" : {"min": 0.4},
                                                    "roi" : Roi.intersection(mask, roi_list = roi),
                                                    "step" : step}    

        if right_seeds is not None and left_seeds is not None:

            segments["external_carotid_artery_right"]["seed"] = voxel2world(right_seeds["external"], itk_image)        
            segments["internal_carotid_artery_right"]["seed"] = voxel2world(right_seeds["internal"], itk_image)
        
            segments["external_carotid_artery_left"]["seed"] = voxel2world(left_seeds["external"], itk_image)       
            segments["internal_carotid_artery_left"]["seed"] = voxel2world(left_seeds["internal"], itk_image)

            try:
                segments["distal_carotid_artery_left"] = {"diameter" : {"min": None, "max": 40},
                                                          "circularity" : {"min": 0.4},
                                                          "roi" : Roi.intersection(mask, roi_list = roi),
                                                          "step" : step,
                                                          "seed" : voxel2world(left_seeds["distal"], itk_image)}         

            except: print("No left distal carotid artery seed was provided")

            try:
                segments["distal_carotid_artery_right"] = {"diameter" : {"min": None, "max": 40},
                                                           "circularity" : {"min": 0.4},
                                                           "roi" : Roi.intersection(mask, roi_list = roi),
                                                           "step" : step,
                                                           "seed" : voxel2world(right_seeds["distal"], itk_image)}         

            except: print("No right distal carotid artery seed was provided")
 
        else:
            # Else, estimate. The problem here is that total segmentator 2.1.0 doesn't generate masks for both of these vessels.
            # Therefore other version of TS is needed such as 2.2.0 using "headneck_bones_vessels" tasks
            print("No manual landmarks provided.")
            # segments["abdominal_aorta"]["seed"] = self._get_seed(mask, affine, segments["abdominal_aorta"]["roi"], 52, p=0.7)

        # Setting the stopping criterions.

        return [
            VesselConfig(
                name = name,
                seed_point = params["seed"],
                segment_every_n_steps = 5,
                step_scheduler = ConstantStepScheduler(params["step"]),
                stopping_criterions = get_stopping_criterions(params, use_circularity),
                centerline_resampling = params["step"],
                vessel_correction = True
            ) for name, params in segments.items()], indices

   

         